apiVersion: v2
name: qnap-trident
description: A Helm chart for deploying Trident CSI Plugin using Trident Operator
type: application
version: 2.0.0
kubeVersion: ">= 1.21.0 <= 1.27"
appVersion: 23.04.0
